"""
Universal Architecture Diagram Generator.

Creates Mermaid diagrams dynamically based on project structure analysis.
"""

from pathlib import Path
from typing import Any


def generate_architecture_diagram(project_path: Path, project_analysis: dict[str, Any]) -> str:
    """Generate Mermaid architecture diagram based on project analysis.

    Args:
        project_path: Path to project
        project_analysis: Analysis from project_analyzer

    Returns:
        Markdown content with Mermaid diagrams
    """
    project_name = project_path.name
    project_type = project_analysis.get("project_type", "unknown")

    # Build diagram based on project type
    if project_type == "python":
        diagram = _generate_python_diagram(project_name, project_analysis)
    elif project_type == "nodejs":
        diagram = _generate_nodejs_diagram(project_name, project_analysis)
    elif project_type == "rust":
        diagram = _generate_rust_diagram(project_name, project_analysis)
    elif project_type == "go":
        diagram = _generate_go_diagram(project_name, project_analysis)
    elif project_type == "atlastrinity":
        diagram = _generate_atlastrinity_diagram(project_name, project_analysis)
    else:
        diagram = _generate_generic_diagram(project_name, project_analysis)

    # Wrap in markdown document
    return f"""# Architecture Diagram - {project_name}

> **Auto-generated by AtlasTrinity MCP devtools**  
> **Project Type:** {project_type}

## System Architecture

{diagram}

---

## Components

{_generate_components_list(project_analysis)}

---

**Last Updated:** Auto-generated  
**Project:** {project_name}  
**Type:** {project_type}
"""


def _generate_python_diagram(project_name: str, analysis: dict[str, Any]) -> str:
    """Generate diagram for Python projects."""
    entry_points = analysis.get("entry_points", ["main.py"])
    components = analysis.get("components", ["Core Logic"])

    # Build flowchart
    nodes = []

    # Entry point
    entry = entry_points[0] if entry_points else "main.py"
    nodes.append(f'    Start(["{entry}"]) --> Init[Initialization]')

    # Components
    if components:
        nodes.append("    Init --> Core{Core Logic}")
        for idx, component in enumerate(components[:5]):  # Limit to 5
            comp_id = f"Comp{idx}"
            nodes.append(f"    Core --> {comp_id}[{component}]")
    else:
        nodes.append("    Init --> Process[Processing]")
        nodes.append("    Process --> Output[Output]")

    # End
    nodes.append("    " + components[-1] if components else "Output" + " --> End([Exit])")

    diagram_code = "\n".join(nodes)

    return f"""```mermaid
flowchart TD
{diagram_code}
    
    style Init fill:#e1f5ff
    style Core fill:#ffe1e1
    style End fill:#e1ffe1
```"""


def _generate_nodejs_diagram(project_name: str, analysis: dict[str, Any]) -> str:
    """Generate diagram for Node.js projects."""
    entry_points = analysis.get("entry_points", ["index.js"])
    components = analysis.get("components", [])

    nodes = []

    # Entry
    entry = entry_points[0] if entry_points else "index.js"
    nodes.append(f'    Start(["{entry}"]) --> Server[Server Setup]')
    nodes.append("    Server --> Routes[Route Handlers]")

    # Components from src/
    if components:
        for idx, component in enumerate(components[:5]):
            comp_id = f"Mod{idx}"
            nodes.append(f"    Routes --> {comp_id}[{component}]")
    else:
        nodes.append("    Routes --> Business[Business Logic]")
        nodes.append("    Business --> DB[Database]")

    diagram_code = "\n".join(nodes)

    return f"""```mermaid
flowchart LR
{diagram_code}
    
    style Server fill:#e1f5ff
    style Routes fill:#ffe1e1
```"""


def _generate_rust_diagram(project_name: str, analysis: dict[str, Any]) -> str:
    """Generate diagram for Rust projects."""
    components = analysis.get("components", ["Core"])

    nodes = [
        '    Start(["main.rs"]) --> Init[Initialization]',
        "    Init --> Core{Core Logic}",
    ]

    for idx, component in enumerate(components[:5]):
        nodes.append(f"    Core --> Mod{idx}[{component}]")

    diagram_code = "\n".join(nodes)

    return f"""```mermaid
flowchart TD
{diagram_code}
    
    style Init fill:#e1f5ff
    style Core fill:#ffe1e1
```"""


def _generate_go_diagram(project_name: str, analysis: dict[str, Any]) -> str:
    """Generate diagram for Go projects."""
    components = analysis.get("components", ["Main"])

    nodes = [
        '    Start(["main.go"]) --> Init[Init]',
        "    Init --> Router[HTTP Router]",
    ]

    for idx, component in enumerate(components[:5]):
        nodes.append(f"    Router --> Handler{idx}[{component}]")

    diagram_code = "\n".join(nodes)

    return f"""```mermaid
flowchart TD
{diagram_code}
    
    style Router fill:#e1f5ff
```"""


def _generate_generic_diagram(project_name: str, analysis: dict[str, Any]) -> str:
    """Generate generic diagram for unknown project types."""
    components = analysis.get("components", ["Module 1", "Module 2"])

    nodes = ["    Start([Application Entry]) --> Init[Initialization]"]

    if components:
        nodes.append("    Init --> Core{Core System}")
        for idx, component in enumerate(components[:5]):
            nodes.append(f"    Core --> Comp{idx}[{component}]")
    else:
        nodes.append("    Init --> Main[Main Logic]")
        nodes.append("    Main --> End([Exit])")

    diagram_code = "\n".join(nodes)

    return f"""```mermaid
flowchart TD
{diagram_code}
    
    style Init fill:#e1f5ff
    style Core fill:#ffe1e1
```"""


def _generate_components_list(analysis: dict[str, Any]) -> str:
    """Generate markdown list of detected components."""
    components = analysis.get("components", [])
    entry_points = analysis.get("entry_points", [])
    key_files = analysis.get("key_files", [])

    sections = []

    if entry_points:
        sections.append("### Entry Points\n" + "\n".join(f"- `{ep}`" for ep in entry_points))

    if components:
        sections.append(
            "### Detected Components\n" + "\n".join(f"- **{comp}**" for comp in components[:10])
        )

    if key_files:
        sections.append(
            "### Key Configuration Files\n" + "\n".join(f"- `{kf}`" for kf in key_files)
        )

    return "\n\n".join(sections) if sections else "*No components detected*"


def _generate_atlastrinity_diagram(project_name: str, analysis: dict[str, Any]) -> str:
    """Generate specialized diagram for AtlasTrinity."""
    components = analysis.get("components", [])

    # Categorize components
    brain_comps = [c.split(".")[1] for c in components if c.startswith("Brain.")]
    mcp_servers = [c.split(".")[1] for c in components if c.startswith("MCP.")]
    frontend = any(c.startswith("Frontend") for c in components)

    nodes = [
        '    subgraph Frontend["Frontend (Electron)"]',
        "        UI[React UI]",
        "        Main[Electron Main]",
        "        UI <--> Main",
        "    end",
        "",
        '    subgraph Core["Brain (Python Core)"]',
        "        Orchestrator{Orchestrator}",
        "        Context[Context Manager]",
        "        Tools[Tool Dispatcher]",
        "        Orchestrator --> Context",
        "        Orchestrator --> Tools",
    ]

    # Add Brain components
    for i, comp in enumerate(brain_comps):
        if comp not in ["Orchestrator", "Context", "Tools", "Mcp_Server"]:  # Skip if already added or special
            nodes.append(f"        Tools --> BrainComp{i}[{comp}]")
    
    nodes.append("    end")
    nodes.append("")
    
    nodes.append('    subgraph MCP["MCP Servers"]')
    for i, server in enumerate(mcp_servers):
        nodes.append(f"        Tools <--> MCP{i}[{server}]")
    nodes.append("    end")

    nodes.append("")
    nodes.append('    subgraph Data["Persistence"]')
    nodes.append("        DB[(SQLite DB)]")
    nodes.append("        Logs[Log Files]")
    nodes.append("    end")

    # Connect major blocks
    nodes.append("    Main <--> Orchestrator")
    nodes.append("    Context --> DB")
    nodes.append("    Orchestrator -.-> Logs")

    diagram_code = "\n".join(nodes)

    return f"""```mermaid
flowchart TD
{diagram_code}

    style Frontend fill:#e1f5ff,stroke:#007acc
    style Core fill:#fff0e6,stroke:#ff6b6b
    style MCP fill:#f0f7e6,stroke:#4caf50
    style Data fill:#f5f5f5,stroke:#666
```"""

