"""Self-Healing Mode Definitions and Configuration Dataclasses.

Defines the operating modes for the unified self-healing hypermodule:
- HEAL: Reactive error fixing
- DIAGNOSE: System health diagnostics
- PREVENT: Preventive maintenance
- IMPROVE: Proactive code improvements
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class HealingMode(Enum):
    """Operating modes for the self-healing hypermodule."""

    HEAL = "heal"  # Reactive — fix an active error
    DIAGNOSE = "diagnose"  # Deep diagnostics of system components
    PREVENT = "prevent"  # Preventive maintenance scan
    IMPROVE = "improve"  # Proactive code improvements


class HealingPriority(Enum):
    """Priority levels for healing operations."""

    CRITICAL = 1  # Immediately blocking task execution
    HIGH = 2  # Service down, but workaround exists
    MEDIUM = 3  # Degraded performance or minor issue
    LOW = 4  # Nice-to-have improvement


class CommitTag(Enum):
    """Git commit tags for self-healing operations."""

    SELF_HEALING = "[Self-Healing]"
    PREVENTION = "[Self-Healing:Prevention]"
    IMPROVEMENT = "[Self-Healing:Improvement]"
    AUTO_FIX = "[Self-Healing:AutoFix]"
    DIAGNOSTICS = "[Self-Healing:Diagnostics]"


@dataclass
class ImprovementNote:
    """A note generated by the LogAnalyzer about potential improvements."""

    id: str
    category: str  # "error_pattern", "slow_operation", "repeated_warning", "resource_bottleneck"
    description: str
    source_file: str | None = None
    source_line: int | None = None
    severity: HealingPriority = HealingPriority.MEDIUM
    occurrences: int = 1
    first_seen: datetime = field(default_factory=datetime.now)
    last_seen: datetime = field(default_factory=datetime.now)
    addressed: bool = False
    fix_applied: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "category": self.category,
            "description": self.description,
            "source_file": self.source_file,
            "source_line": self.source_line,
            "severity": self.severity.name,
            "occurrences": self.occurrences,
            "first_seen": self.first_seen.isoformat(),
            "last_seen": self.last_seen.isoformat(),
            "addressed": self.addressed,
            "fix_applied": self.fix_applied,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ImprovementNote":
        return cls(
            id=data["id"],
            category=data["category"],
            description=data["description"],
            source_file=data.get("source_file"),
            source_line=data.get("source_line"),
            severity=HealingPriority[data.get("severity", "MEDIUM")],
            occurrences=data.get("occurrences", 1),
            first_seen=datetime.fromisoformat(data["first_seen"]),
            last_seen=datetime.fromisoformat(data["last_seen"]),
            addressed=data.get("addressed", False),
            fix_applied=data.get("fix_applied"),
        )


@dataclass
class Hotspot:
    """A code location identified for improvement."""

    file_path: str
    description: str
    priority: HealingPriority
    category: str  # "performance", "error_handling", "code_quality", "security"
    suggested_fix: str | None = None
    related_notes: list[str] = field(default_factory=list)  # ImprovementNote IDs

    def to_dict(self) -> dict[str, Any]:
        return {
            "file_path": self.file_path,
            "description": self.description,
            "priority": self.priority.name,
            "category": self.category,
            "suggested_fix": self.suggested_fix,
            "related_notes": self.related_notes,
        }


@dataclass
class DiagnosticReport:
    """Unified diagnostic report from all checks."""

    timestamp: datetime = field(default_factory=datetime.now)
    checks: dict[str, dict[str, Any]] = field(default_factory=dict)
    overall_status: str = "unknown"  # "healthy", "degraded", "critical"
    issues_found: int = 0
    auto_fixed: int = 0
    recommendations: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp.isoformat(),
            "checks": self.checks,
            "overall_status": self.overall_status,
            "issues_found": self.issues_found,
            "auto_fixed": self.auto_fixed,
            "recommendations": self.recommendations,
        }


@dataclass
class HealingResult:
    """Result of a healing operation."""

    mode: HealingMode
    success: bool
    message: str
    details: dict[str, Any] = field(default_factory=dict)
    committed: bool = False
    commit_hash: str | None = None
    duration_seconds: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "mode": self.mode.value,
            "success": self.success,
            "message": self.message,
            "details": self.details,
            "committed": self.committed,
            "commit_hash": self.commit_hash,
            "duration_seconds": self.duration_seconds,
        }
