#!/bin/bash

# 🚀 AtlasTrinity Native Deployment Script
# Розгортка Windsurf MCP без Docker

set -e

echo "🌊 AtlasTrinity Native Deployment Script"
echo "=================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Helper functions
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Get project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
log_info "Project root: $PROJECT_ROOT"

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check Swift
    if ! command -v swift &> /dev/null; then
        log_error "Swift not found. Please install Xcode Command Line Tools:"
        echo "  xcode-select --install"
        exit 1
    fi
    SWIFT_VERSION=$(swift --version | head -n1)
    log_success "Swift found: $SWIFT_VERSION"
    
    # Check Python
    if ! command -v python3 &> /dev/null; then
        log_error "Python 3 not found"
        exit 1
    fi
    PYTHON_VERSION=$(python3 --version)
    log_success "Python found: $PYTHON_VERSION"
    
    # Check Node.js
    if ! command -v node &> /dev/null; then
        log_error "Node.js not found"
        exit 1
    fi
    NODE_VERSION=$(node --version)
    log_success "Node.js found: $NODE_VERSION"
    
    # Check npm
    if ! command -v npm &> /dev/null; then
        log_error "npm not found"
        exit 1
    fi
    NPM_VERSION=$(npm --version)
    log_success "npm found: $NPM_VERSION"
}

# Build Windsurf MCP server
build_windsurf_mcp() {
    log_info "Building Windsurf MCP server..."
    
    MCP_PATH="$PROJECT_ROOT/vendor/mcp-server-windsurf"
    BINARY_PATH="$MCP_PATH/.build/release/mcp-server-windsurf"
    
    if [ ! -d "$MCP_PATH" ]; then
        log_error "Windsurf MCP source not found at $MCP_PATH"
        exit 1
    fi
    
    # Check if binary exists and is recent
    if [ -f "$BINARY_PATH" ]; then
        BINARY_AGE=$(($(date +%s) - $(stat -f %m "$BINARY_PATH")))
        if [ $BINARY_AGE -lt 604800 ];  # 7 days
            log_success "Windsurf MCP binary is recent ($(($BINARY_AGE / 86400)) days old)"
            return 0
        else
            log_warning "Windsurf MCP binary is old ($(($BINARY_AGE / 86400)) days). Rebuilding..."
        fi
    fi
    
    # Build the server
    log_info "Running 'swift build --configuration release'..."
    cd "$MCP_PATH"
    
    if ! swift build --configuration release; then
        log_error "Failed to build Windsurf MCP server"
        exit 1
    fi
    
    # Verify binary exists
    if [ ! -f "$BINARY_PATH" ]; then
        log_error "Binary not found after build at $BINARY_PATH"
        exit 1
    fi
    
    # Set executable permissions
    chmod +x "$BINARY_PATH"
    
    log_success "Windsurf MCP server built successfully"
    log_info "Binary location: $BINARY_PATH"
}

# Setup configuration
setup_configuration() {
    log_info "Setting up configuration..."
    
    CONFIG_DIR="$HOME/.config/atlastrinity"
    ENV_FILE="$CONFIG_DIR/.env"
    CONFIG_FILE="$CONFIG_DIR/config.yaml"
    
    # Create config directory
    mkdir -p "$CONFIG_DIR"
    
    # Setup .env file if not exists
    if [ ! -f "$ENV_FILE" ]; then
        log_info "Creating .env file..."
        cat > "$ENV_FILE" << EOF
# AtlasTrinity Environment Variables
# Generated by native deployment script

# MCP Configuration
MCP_DIR="$CONFIG_DIR"
PROJECT_ROOT="$PROJECT_ROOT"

# API Keys (replace with your actual keys)
WINDSURF_API_KEY=sk-ws-your-api-key-here
COPILOT_API_KEY=ghp-your-github-token-here

# Development Settings
PYTHONPATH="$PROJECT_ROOT:$PYTHONPATH"
NODE_ENV=development
EOF
        log_success "Created .env file at $ENV_FILE"
        log_warning "Please update API keys in $ENV_FILE"
    else
        log_info ".env file already exists at $ENV_FILE"
    fi
    
    # Setup config.yaml if not exists
    if [ ! -f "$CONFIG_FILE" ]; then
        log_info "Creating config.yaml file..."
        cat > "$CONFIG_FILE" << EOF
# AtlasTrinity Configuration
# Generated by native deployment script

# MCP Server Configuration
mcp:
  mcpServers:
    _defaults:
      connect_timeout: 30
    
    # Windsurf MCP Server (Native Binary)
    windsurf:
      command: "\${PROJECT_ROOT}/vendor/mcp-server-windsurf/.build/release/mcp-server-windsurf"
      description: "Windsurf AI with Cascade Action Phase (Native)"
      tier: 1
      agents: ["atlas", "tetyana", "grisha"]
      disabled: false
      env:
        WINDSURF_API_KEY: "\${WINDSURF_API_KEY}"
        PYTHONPATH: "\${PROJECT_ROOT}"
        MCP_DIR: "\${MCP_DIR}"
    
    # Vibe Server
    vibe:
      command: "python3"
      args: ["-m", "src.mcp_server.vibe_server"]
      description: "Vibe AI Assistant"
      tier: 2
      agents: ["atlas", "tetyana", "grisha"]
      disabled: false
      env:
        PYTHONPATH: "\${PROJECT_ROOT}"
        MCP_DIR: "\${MCP_DIR}"
    
    # DevTools Server
    devtools:
      command: "node"
      args: ["src/mcp_server/react_devtools_mcp.js"]
      description: "React DevTools integration"
      tier: 3
      agents: ["atlas"]
      disabled: false
      env:
        NODE_ENV: "development"
        MCP_DIR: "\${MCP_DIR}"

# System Configuration
system:
  workspace_path: "\${PROJECT_ROOT}"
  config_root: "\${CONFIG_DIR}"

# Brain Configuration
brain:
  log_level: "info"
  max_memory_mb: 2048
  enable_mcp: true
  enable_plugins: true
EOF
        log_success "Created config.yaml file at $CONFIG_FILE"
    else
        log_info "config.yaml file already exists at $CONFIG_FILE"
    fi
}

# Validate installation
validate_installation() {
    log_info "Validating installation..."
    
    BINARY_PATH="$PROJECT_ROOT/vendor/mcp-server-windsurf/.build/release/mcp-server-windsurf"
    
    # Check binary exists
    if [ ! -f "$BINARY_PATH" ]; then
        log_error "Windsurf MCP binary not found at $BINARY_PATH"
        exit 1
    fi
    
    # Check binary is executable
    if [ ! -x "$BINARY_PATH" ]; then
        log_error "Windsurf MCP binary is not executable"
        exit 1
    fi
    
    # Test binary
    log_info "Testing Windsurf MCP binary..."
    if ! "$BINARY_PATH" --help &> /dev/null; then
        log_warning "Binary test failed, but this might be normal"
    else
        log_success "Windsurf MCP binary test passed"
    fi
    
    # Check configuration
    CONFIG_FILE="$HOME/.config/atlastrinity/config.yaml"
    if [ ! -f "$CONFIG_FILE" ]; then
        log_error "Configuration file not found at $CONFIG_FILE"
        exit 1
    fi
    
    log_success "Installation validation passed"
}

# Test MCP integration
test_mcp_integration() {
    log_info "Testing MCP integration..."
    
    cd "$PROJECT_ROOT"
    
    # Test MCP status
    if npm run mcp:status &> /dev/null; then
        log_success "MCP status check passed"
    else
        log_warning "MCP status check failed"
    fi
    
    # Test Windsurf MCP specifically
    if python3 -c "
import sys
sys.path.insert(0, 'src')
from brain.mcp.mcp_manager import MCPManager
import asyncio

async def test():
    manager = MCPManager()
    session = await manager.get_session('windsurf')
    if session:
        print('✅ Windsurf MCP connection successful')
        return True
    else:
        print('❌ Windsurf MCP connection failed')
        return False

result = asyncio.run(test())
sys.exit(0 if result else 1)
" &> /dev/null; then
        log_success "Windsurf MCP integration test passed"
    else
        log_warning "Windsurf MCP integration test failed"
    fi
}

# Create startup script
create_startup_script() {
    log_info "Creating startup script..."
    
    STARTUP_SCRIPT="$PROJECT_ROOT/scripts/start_windsurf_native.sh"
    mkdir -p "$(dirname "$STARTUP_SCRIPT")"
    
    cat > "$STARTUP_SCRIPT" << EOF
#!/bin/bash

# Windsurf MCP Native Startup Script
# Generated by native deployment script

set -e

PROJECT_ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
BINARY_PATH="\$PROJECT_ROOT/vendor/mcp-server-windsurf/.build/release/mcp-server-windsurf"

echo "🚀 Starting Windsurf MCP Server (Native)..."
echo "Binary: \$BINARY_PATH"

# Check if binary exists
if [ ! -f "\$BINARY_PATH" ]; then
    echo "❌ Binary not found. Please run deployment script first."
    exit 1
fi

# Set environment variables
export PYTHONPATH="\$PROJECT_ROOT:\$PYTHONPATH"
export MCP_DIR="\$HOME/.config/atlastrinity"

# Load environment variables
if [ -f "\$HOME/.config/atlastrinity/.env" ]; then
    export \$(grep -v '^#' "\$HOME/.config/atlastrinity/.env" | xargs)
fi

# Start the server
echo "🌊 Starting Windsurf MCP server..."
exec "\$BINARY_PATH"
EOF
    
    chmod +x "$STARTUP_SCRIPT"
    log_success "Created startup script at $STARTUP_SCRIPT"
}

# Create systemd service (optional)
create_systemd_service() {
    if command -v systemctl &> /dev/null; then
        log_info "Creating systemd service..."
        
        SERVICE_FILE="/tmp/atlastrinity-windsurf.service"
        
        cat > "$SERVICE_FILE" << EOF
[Unit]
Description=AtlasTrinity Windsurf MCP Service
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$PROJECT_ROOT
Environment=PYTHONPATH=$PROJECT_ROOT:$PYTHONPATH
Environment=MCP_DIR=$HOME/.config/atlastrinity
ExecStart=$PROJECT_ROOT/vendor/mcp-server-windsurf/.build/release/mcp-server-windsurf
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
        
        log_info "Systemd service file created at $SERVICE_FILE"
        log_info "To install: sudo systemctl enable --now $SERVICE_FILE"
    else
        log_info "systemd not available, skipping service creation"
    fi
}

# Main execution
main() {
    echo
    echo "🚀 AtlasTrinity Native Deployment"
    echo "================================="
    echo
    
    check_prerequisites
    build_windsurf_mcp
    setup_configuration
    validate_installation
    test_mcp_integration
    create_startup_script
    create_systemd_service
    
    echo
    echo "✅ Native deployment completed successfully!"
    echo
    echo "📋 Next steps:"
    echo "1. Update API keys in ~/.config/atlastrinity/.env"
    echo "2. Start the application: npm run dev"
    echo "3. Or start Windsurf MCP only: $PROJECT_ROOT/scripts/start_windsurf_native.sh"
    echo "4. Check MCP status: npm run mcp:status"
    echo
    echo "🔧 Configuration files:"
    echo "   - Config: ~/.config/atlastrinity/config.yaml"
    echo "   - Environment: ~/.config/atlastrinity/.env"
    echo "   - Binary: $PROJECT_ROOT/vendor/mcp-server-windsurf/.build/releasemcp-server-windsurf"
    echo
    echo "🚀 Ready to run AtlasTrinity with native Windsurf MCP!"
}

# Run main function
main "$@"
